# load GLODAPv2.2020

library(tidyverse)
library(lubridate)
library(here)


colspec <- cols(
  G2cruise = col_integer(),
  G2station = col_integer(),
  G2cast = col_integer(),
  G2year = col_integer(),
  G2month = col_integer(),
  G2day = col_integer(),
  G2hour = col_integer(),
  G2minute = col_integer(),
  G2latitude = col_double(),
  G2longitude = col_double(),
  G2bottomdepth = col_double(),
  G2maxsampdepth = col_double(),
  G2bottle = col_integer(),
  G2pressure = col_double(),
  G2depth = col_double(),
  G2temperature = col_double(),
  G2theta = col_double(),
  G2salinity = col_double(),
  G2salinityf = col_integer(),
  G2salinityqc = col_double(),
  G2sigma0 = col_double(),
  G2sigma1 = col_double(),
  G2sigma2 = col_double(),
  G2sigma3 = col_double(),
  G2sigma4 = col_double(),
  G2gamma = col_double(),
  G2oxygen = col_double(),
  G2oxygenf = col_integer(),
  G2oxygenqc = col_double(),
  G2aou = col_double(),
  G2aouf = col_integer(),
  G2nitrate = col_double(),
  G2nitratef = col_integer(),
  G2nitrateqc = col_double(),
  G2nitrite = col_double(),
  G2nitritef = col_double(),
  G2silicate = col_double(),
  G2silicatef = col_double(),
  G2silicateqc = col_double(),
  G2phosphate = col_double(),
  G2phosphatef = col_double(),
  G2phosphateqc = col_double(),
  G2tco2 = col_double(),
  G2tco2f = col_double(),
  G2tco2qc = col_double(),
  G2talk = col_double(),
  G2talkf = col_double(),
  G2talkqc = col_double(),
  G2fco2 = col_double(),
  G2fco2f = col_double(),
  G2fco2temp = col_double(),
  G2phts25p0 = col_double(),
  G2phts25p0f = col_double(),
  G2phtsinsitutp = col_double(),
  G2phtsinsitutpf = col_double(),
  G2phtsqc = col_double(),
  G2cfc11 = col_double(),
  G2pcfc11 = col_double(),
  G2cfc11f = col_double(),
  G2cfc11qc = col_double(),
  G2cfc12 = col_double(),
  G2pcfc12 = col_double(),
  G2cfc12f = col_double(),
  G2cfc12qc = col_double(),
  G2cfc113 = col_double(),
  G2pcfc113 = col_double(),
  G2cfc113f = col_double(),
  G2cfc113qc = col_double(),
  G2ccl4 = col_double(),
  G2pccl4 = col_double(),
  G2ccl4f = col_double(),
  G2ccl4qc = col_double(),
  G2sf6 = col_double(),
  G2psf6 = col_double(),
  G2sf6f = col_double(),
  G2c13 = col_double(),
  G2c13f = col_integer(),
  G2c13qc = col_double(),
  G2c14 = col_double(),
  G2c14f = col_integer(),
  G2c14err = col_double(),
  G2h3 = col_double(),
  G2h3f = col_double(),
  G2h3err = col_double(),
  G2he3 = col_double(),
  G2he3f = col_double(),
  G2he3err = col_double(),
  G2he = col_double(),
  G2hef = col_double(),
  G2heerr = col_double(),
  G2neon = col_double(),
  G2neonf = col_double(),
  G2neonerr = col_double(),
  G2o18 = col_double(),
  G2o18f = col_double(),
  G2toc = col_double(),
  G2tocf = col_double(),
  G2doc = col_double(),
  G2docf = col_double(),
  G2don = col_double(),
  G2donf = col_double(),
  G2tdn = col_double(),
  G2tdnf = col_double(),
  G2chla = col_double(),
  G2chlaf = col_double()
)

glodapv2 <- read_csv(here("data/GLODAPv2.2020_Merged_Master_File.csv"), 
                   col_types = colspec, 
                   na = c("NA", "-9999"))
expcodes <- read_delim(here("data/expocodes.txt"), 
                       delim = "\t", 
                       col_names = c("num", "cruise"))

# pick what we need from GLODAP
glodapv2_dic <- glodapv2 %>%
  filter(!is.na(G2c14) | !is.na(G2c13)) %>%
  mutate(collection_time = ymd_hm(paste(G2year, G2month, G2day, G2hour, G2minute, sep = "-"))) %>%
  select(G2cruise, G2station, G2cast, collection_time, 
         G2latitude, G2longitude, G2bottomdepth, G2maxsampdepth, 
         G2bottle, G2pressure, G2depth, G2temperature, G2theta, G2salinity,
         G2sigma0, G2sigma1, G2sigma2, G2sigma3, G2sigma4, 
         G2oxygen, G2aou, G2nitrate, G2silicate, G2phosphate, G2tco2, G2talk,
         G2c13, G2c13f, G2c14, G2c14f, G2c14err) %>%
  inner_join(expcodes, by = c("G2cruise" = "num")) %>%
  rename(expocode = cruise)

write_csv(glodapv2_dic, here("data/glodapv2_dic.csv"))


