---
title: "NOSAMS_secondaries"
author: "Ann McNichol"
date: "12/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load libraries and data

```{r}
library(tidyverse)
library(here)

nosams <- read_csv(here("data/ann_jul_17_QA_R.csv"))

```

# boxplot of 13C data for secondaries


```{r}
fill <- "#4271AE"
line <- "#1F3552"

d13C_box <- ggplot(nosams, aes(x = as.factor(RN2), y = d13C_1)) +
  geom_boxplot(fill = fill, color = line) +
  scale_x_discrete(name = "Receipt Number") +
  scale_y_continuous(name = "d13C, o/oo", breaks = seq(-1.0,1.5, 0.25), limits = c(-1.0, 1.5)) +
  ggtitle("Boxplot of mean DI13C for NOSAMS secondary standards") +
  theme_bw() + 
  geom_jitter(alpha = 0.4, size = 0.2)
d13C_box
```

#now to figure out how to extract the statistics

```{r}
fill <- "#4271AE"
line <- "#1F3552"

d13C_box_stats <- boxplot(d13C_1 ~ RN2, data = nosams) 
d13C_box_stats

```

#calculate mean and stdev for each RN; also select and look at weird results

```{r}
nosams %>% 
  group_by(RN2) %>%
  summarize(avg = mean(d13C_1, na.rm = TRUE), stand = sd(d13C_1, na.rm=TRUE), num = n())


nosams %>%
  filter(RN2 == 2) %>%
  select(RN2, d13C_1)
```

#generate and save data in csv file

```{r}
nosams_sum <- nosams %>% 
  group_by(RN2) %>%
  summarize(avg = mean(d13C_1, na.rm = TRUE), 
            stand = sd(d13C_1, na.rm=TRUE), 
            num = n())

write_csv(nosams_sum, here("data/secondarysum.csv"))
```

