---
title: "DIC duplicates"
output:
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(here)

nosams <- read_csv(here("data/nosams_clivar.csv"))
```


Let's find field duplicates for Ann. This only takes samples that are the same bottle with different rec_nums.

```{r}
field_dups <- nosams %>% 
  group_by(expocode, station, cast, bottle) %>%
  mutate(N = n()) %>%
  filter(N > 1,
         length(unique(rec_num)) > 1) %>%
  arrange(rec_num)
```

Why not lab dupes while we're at it? These are samples that have multiples of the same receipt number, which are presumably the same water.

```{r}
recnum_dups <- nosams %>% 
  group_by(rec_num) %>%
  mutate(N = n()) %>%
  filter(N > 1) %>%
  arrange(rec_num)
```
```{r}
write_csv(field_dups, here("data/field_dups.csv"))
write_csv(recnum_dups, here("data/recnum_dups.csv"))
```
```{r}
field_dups<- read_csv(here("data/field_dups.csv"))
ggplot(field_dups, aes(collection_date, f_modern)) +
  geom_point()

field_dups %>% filter(is.na(collection_date))
field_dups %>% filter(is.na(f_modern))
nosams %>% filter(collection_date > "1/1/1994", collection_date < "1/1/2005") %>% view()
```

